### ISSUE TITLE
Error message/exception when server connection parameters are wrong should be more informative

### ISSUE THREAD

**Issue by myrle-krantz** [stellar/java-stellar-sdk#17]
Exception in thread "main" com.google.gson.JsonSyntaxException: java.lang.IllegalStateException: Not a JSON Object: "<b>Welcome"
    at com.google.gson.Gson.fromJson(Gson.java:826)
    at com.google.gson.Gson.fromJson(Gson.java:779)
    at com.google.gson.Gson.fromJson(Gson.java:728)
    at org.stellar.sdk.requests.ResponseHandler.handleResponse(ResponseHandler.java:45)
    at org.apache.http.client.fluent.Response.handleResponse(Response.java:90)
    at org.stellar.sdk.requests.AccountsRequestBuilder.execute(AccountsRequestBuilder.java:35)
    at org.stellar.sdk.requests.AccountsRequestBuilder.execute(AccountsRequestBuilder.java:39)
    at org.mifos.connector.stellar.SendTransaction.main(SendTransaction.java:17)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
    at java.lang.reflect.Method.invoke(Method.java:606)
    at com.intellij.rt.execution.application.AppMain.main(AppMain.java:144)

**Comment by overcat** [comment]
Since this issue has been inactive for a long time and a lot of things have changed, I decided to close it. If there are any further issues later on, feel free to reopen it.
