### ISSUE TITLE
Timeout is required for market offer, why does not use the default from `okHttp`?

### ISSUE THREAD

**Issue by dabitdev** [stellar/java-stellar-sdk#174]
``` 
Process: com.blockeq.stellarwallet, PID: 3930
    java.lang.RuntimeException: TimeBounds has to be set or you must call setTimeout(TIMEOUT_INFINITE).
        at org.stellar.sdk.Transaction$Builder.build(Transaction.java:370)
        at com.blockeq.stellarwallet.remote.Horizon$getCreateMarketOffer$1.run(Horizon.kt:330)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:245)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:764)
```

**Comment by bartekn** [comment]
This is not connect/read timeout. This is timeout set on a transaction, it will be invalid after that time.

More info: https://github.com/stellar/stellar-core/issues/1811
