### ISSUE TITLE
Order book streaming accidentally interrupted with exception

### ISSUE THREAD

**Issue by stepan-romankov** [stellar/java-stellar-sdk#210]
```
Exception in thread "OkHttp Dispatcher" java.lang.IllegalStateException: Failed 200
	at org.stellar.sdk.requests.SSEStream$StellarEventSourceListener.onFailure(SSEStream.java:186)
	at shadow.okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:83)
	at shadow.okhttp3.internal.sse.RealEventSource.onResponse(RealEventSource.java:54)
	at shadow.okhttp3.RealCall$AsyncCall.execute(RealCall.java:153)
	at shadow.okhttp3.internal.NamedRunnable.run(NamedRunnable.java:32)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: java.io.EOFException
	at shadow.okio.RealBufferedSource.require(RealBufferedSource.java:61)
	at shadow.okio.RealBufferedSource.readHexadecimalUnsignedLong(RealBufferedSource.java:304)
	at shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.readChunkSize(Http1Codec.java:469)
	at shadow.okhttp3.internal.http1.Http1Codec$ChunkedSource.read(Http1Codec.java:449)
	at shadow.okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:394)
	at shadow.okio.RealBufferedSource.indexOfElement(RealBufferedSource.java:383)
	at shadow.okhttp3.internal.sse.ServerSentEventReader.processNextEvent(ServerSentEventReader.java:61)
	at shadow.okhttp3.internal.sse.RealEventSource.processResponse(RealEventSource.java:80)
	... 6 more
```

**Comment by stepan-romankov** [comment]
@overcat any ideas?

**Comment by stepan-romankov** [comment]
@tamirms?
