### ISSUE TITLE
server.payments().execute() throws java.lang.IllegalArgumentException: not a valid GroupElement

### ISSUE THREAD

**Issue by efritze** [stellar/java-stellar-sdk#230]
```
Server server = new Server("https://horizon.stellar.org");

String forwardCursor = "106239095558123521";
Page<OperationResponse> pages = server.payments().cursor(forwardCursor).order(RequestBuilder.Order.ASC).limit(200).execute();

```
 
The code above throws the following exception.

```
java.lang.IllegalArgumentException: not a valid GroupElement

	at shadow.net.i2p.crypto.eddsa.math.GroupElement.<init>(GroupElement.java:336)
	at shadow.net.i2p.crypto.eddsa.math.GroupElement.<init>(GroupElement.java:287)
	at shadow.net.i2p.crypto.eddsa.spec.EdDSAPublicKeySpec.<init>(EdDSAPublicKeySpec.java:36)
	at org.stellar.sdk.KeyPair.fromPublicKey(KeyPair.java:114)
	at org.stellar.sdk.KeyPair.fromAccountId(KeyPair.java:105)
	at org.stellar.sdk.responses.KeyPairTypeAdapter.read(KeyPairTypeAdapter.java:19)
	at org.stellar.sdk.responses.KeyPairTypeAdapter.read(KeyPairTypeAdapter.java:11)
	at shadow.com.google.gson.TypeAdapter$1.read(TypeAdapter.java:199)
	at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:994)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:967)
	at org.stellar.sdk.responses.OperationDeserializer.deserialize(OperationDeserializer.java:26)
	at org.stellar.sdk.responses.OperationDeserializer.deserialize(OperationDeserializer.java:15)
	at shadow.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at shadow.com.google.gson.internal.bind.TypeAdapterRuntimeTypeWrapper.read(TypeAdapterRuntimeTypeWrapper.java:41)
	at shadow.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:82)
	at shadow.com.google.gson.internal.bind.CollectionTypeAdapterFactory$Adapter.read(CollectionTypeAdapterFactory.java:61)
	at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131)
	at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:994)
	at org.stellar.sdk.responses.PageDeserializer.deserialize(PageDeserializer.java:49)
	at org.stellar.sdk.responses.PageDeserializer.deserialize(PageDeserializer.java:19)
	at shadow.com.google.gson.internal.bind.TreeTypeAdapter.read(TreeTypeAdapter.java:69)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:927)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:892)
	at shadow.com.google.gson.Gson.fromJson(Gson.java:841)
	at org.stellar.sdk.requests.ResponseHandler.handleResponse(ResponseHandler.java:42)
	at org.stellar.sdk.requests.PaymentsRequestBuilder.execute(PaymentsRequestBuilder.java:70)
	at org.stellar.sdk.requests.PaymentsRequestBuilder.execute(PaymentsRequestBuilder.java:94)

```

**Comment by tamirms** [comment]
@efritze this issue should be fixed in the 0.9.0 release
