### ISSUE TITLE
shadow.com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "18446744073709551524"

### ISSUE THREAD

**Issue by TimC71** [stellar/java-stellar-sdk#391]
### What version are you using?
java-stellar-sdk-0.29.0.jar

### What did you do?
`    public static void main(String[] args) throws IOException {
        Page<EffectResponse> page = server.effects().forLedger(38517886).cursor("165433060681412610-3")
                .order(RequestBuilder.Order.ASC).limit(1).execute();
        System.out.println("done");
    }`

### What did you expect to see?
Response with success and failed effects

### What did you see instead?

`shadow.com.google.gson.JsonSyntaxException: java.lang.NumberFormatException: For input string: "18446744073709551524"
        at shadow.com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:306) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.internal.bind.TypeAdapters$11.read(TypeAdapters.java:296) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$1.read(ReflectiveTypeAdapterFactory.java:131) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.internal.bind.ReflectiveTypeAdapterFactory$Adapter.read(ReflectiveTypeAdapterFactory.java:222) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.Gson.fromJson(Gson.java:927) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.Gson.fromJson(Gson.java:994) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at shadow.com.google.gson.Gson.fromJson(Gson.java:967) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at org.stellar.sdk.responses.EffectDeserializer.deserialize(EffectDeserializer.java:38) ~[java-stellar-sdk-0.29.0.jar:0.29.0]
        at org.stellar.sdk.responses.EffectDeserializer.deserialize(EffectDeserializer.java:18) ~[java-stellar-sdk-0.29.0.jar:0.29.0]`

**Comment by vinamogit** [comment]
Already fixed by #388
