### ISSUE TITLE
Demo code giving error

### ISSUE THREAD

**Issue by ronaksv** [stellar/java-stellar-sdk#79]
I ran the demo code to "Receive Payments" (https://www.stellar.org/developers/guides/get-started/transactions.html) with a simple Java program. 
I had already created an account and other services like "get balance", "make payment" all were working fine. But when I tried to run the "Receive Payments" program, I got the following error

Exception in thread "main" java.lang.RuntimeException: RESTEASY003940: Unable to instantiate MessageBodyReader
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1465)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1396)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1317)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:2490)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:99)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:38)
	at org.jboss.resteasy.util.FeatureContextDelegate.register(FeatureContextDelegate.java:12)
	at org.glassfish.jersey.media.sse.SseFeature.configure(SseFeature.java:136)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1767)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1396)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1317)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.register(ResteasyProviderFactory.java:2490)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.register(ResteasyClientBuilder.java:416)
	at org.jboss.resteasy.client.jaxrs.ResteasyClientBuilder.register(ResteasyClientBuilder.java:35)
	at org.stellar.sdk.requests.PaymentsRequestBuilder.stream(PaymentsRequestBuilder.java:87)
	at com.eno.ron.XLMTest.main(XLMTest.java:105)
Caused by: java.lang.IllegalArgumentException: RESTEASY003900: Unable to find a public constructor for provider class org.glassfish.jersey.media.sse.EventInputReader
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createConstructorInjector(ResteasyProviderFactory.java:2307)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.createProviderInstance(ResteasyProviderFactory.java:2296)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.addMessageBodyReader(ResteasyProviderFactory.java:809)
	at org.jboss.resteasy.spi.ResteasyProviderFactory.registerProvider(ResteasyProviderFactory.java:1460)
	... 15 more

Can you please point out what exactly I am doing wrong here

**Comment by overcat** [comment]
Due to the long period of inactivity on this issue, I have decided to close it. If there are any more problems, please don't hesitate to reopen it.
